### ISSUE TITLE
Responsiveness up to 240 px at least

### ISSUE THREAD

**Issue by valadas** [eraware/Dnn.Platform#21]
Given that the smalest commonly used mobile devices are 320px wide and that the persona bar is 80px wide, this leaves a 240px usable in the panel, so we need to make at least the components to be somehow usable at 240px wide. Ideally 220px to allow a little padding too. This will not solve the persona bar responsiveness but we should at least make the new components as such if we hope to have a responsive persona bar one day...

@david-poindexter this will be very easy with flexbox and I already have tested something here but not coded it yet, we we talk, just wanted to have this logged as an issue here.

**Comment by valadas** [comment]
I have unassigned myself in case you have a better way to handle this... @david-poindexter

**Comment by david-poindexter** [comment]
Closing issue per #33
